export const deAuthLocalization = {
    APP: "App",
    ACCOUNT: "Konto",
    ACCOUNTS: "Konten",
    ACCOUNTS_DESCRIPTION: "Zwischen aktuell angemeldeten Konten wechseln.",
    ACCOUNTS_INSTRUCTIONS: "Mit einem weiteren Konto anmelden.",
    ADD_ACCOUNT: "Konto hinzufügen",
    SWITCH_ACCOUNT: "Konto wechseln",
    PERSONAL_ACCOUNT: "Persönliches Konto",
    USER: "Benutzer",

    ALREADY_HAVE_AN_ACCOUNT: "Bereits ein Konto?",
    DONT_HAVE_AN_ACCOUNT: "Noch kein Konto?",

    SIGN_IN: "Anmelden",
    SIGN_IN_ACTION: "Anmelden",
    SIGN_IN_DESCRIPTION: "Melden Sie sich mit Ihren Zugangsdaten an.",
    SIGN_IN_USERNAME_DESCRIPTION: "Melden Sie sich mit Benutzername oder E-Mail-Adresse an.",
    SIGN_IN_USERNAME_PLACEHOLDER: "Benutzername oder E-Mail",
    SIGN_IN_WITH: "Anmelden mit",

    SIGN_UP: "Registrieren",
    SIGN_UP_ACTION: "Konto erstellen",
    SIGN_UP_DESCRIPTION: "Erstellen Sie ein neues Konto.",
    SIGN_UP_EMAIL: "Prüfen Sie Ihre E-Mails, um die Registrierung abzuschließen.",

    EMAIL: "E-Mail",
    EMAIL_DESCRIPTION: "Geben Sie Ihre E-Mail-Adresse ein.",
    EMAIL_INSTRUCTIONS: "Bitte eine gültige E-Mail-Adresse eingeben.",
    EMAIL_IS_THE_SAME: "Die E-Mail-Adresse ist unverändert",
    EMAIL_PLACEHOLDER: "max@beispiel.de",
    EMAIL_REQUIRED: "E-Mail-Adresse ist erforderlich",
    EMAIL_VERIFY_CHANGE: "Bitte bestätigen Sie die Änderung über den Link in Ihrer E-Mail.",

    USERNAME: "Benutzername",
    USERNAME_DESCRIPTION: "Geben Sie Ihren Benutzernamen ein.",
    USERNAME_INSTRUCTIONS: "Maximal 32 Zeichen verwenden.",
    USERNAME_PLACEHOLDER: "Benutzername",

    NAME: "Name",
    NAME_DESCRIPTION: "Geben Sie Ihren Namen ein.",
    NAME_INSTRUCTIONS: "Maximal 32 Zeichen verwenden.",
    NAME_PLACEHOLDER: "Name",

    PASSWORD: "Passwort",
    PASSWORD_PLACEHOLDER: "Passwort",
    PASSWORD_REQUIRED: "Passwort ist erforderlich",
    PASSWORDS_DO_NOT_MATCH: "Die Passwörter stimmen nicht überein",

    CONFIRM_PASSWORD: "Passwort bestätigen",
    CONFIRM_PASSWORD_PLACEHOLDER: "Passwort erneut eingeben",
    CONFIRM_PASSWORD_REQUIRED: "Passwortbestätigung ist erforderlich",

    CURRENT_PASSWORD: "Aktuelles Passwort",
    CURRENT_PASSWORD_PLACEHOLDER: "Aktuelles Passwort",

    NEW_PASSWORD: "Neues Passwort",
    NEW_PASSWORD_PLACEHOLDER: "Neues Passwort",
    NEW_PASSWORD_REQUIRED: "Neues Passwort ist erforderlich",

    FORGOT_PASSWORD: "Passwort vergessen",
    FORGOT_PASSWORD_ACTION: "Link zum Zurücksetzen senden",
    FORGOT_PASSWORD_DESCRIPTION: "Geben Sie Ihre E-Mail-Adresse ein, um Ihr Passwort zurückzusetzen.",
    FORGOT_PASSWORD_EMAIL: "Prüfen Sie Ihre E-Mails auf den Link zum Zurücksetzen.",
    FORGOT_PASSWORD_LINK: "Passwort vergessen?",

    RESET_PASSWORD: "Passwort zurücksetzen",
    RESET_PASSWORD_ACTION: "Passwort zurücksetzen",
    RESET_PASSWORD_DESCRIPTION: "Geben Sie ein neues Passwort ein.",
    RESET_PASSWORD_SUCCESS: "Das Passwort wurde erfolgreich zurückgesetzt.",

    EMAIL_VERIFICATION: "E-Mail-Bestätigung",
    EMAIL_VERIFICATION_DESCRIPTION: "Bitte bestätigen Sie Ihre E-Mail-Adresse.",
    EMAIL_VERIFICATION_SUCCESS: "E-Mail-Adresse erfolgreich bestätigt.",

    VERIFY_YOUR_EMAIL: "E-Mail-Adresse bestätigen",
    VERIFY_YOUR_EMAIL_DESCRIPTION: "Bitte prüfen Sie Ihren Posteingang und bestätigen Sie Ihre E-Mail-Adresse.",
    RESEND_VERIFICATION_EMAIL: "Bestätigungs-E-Mail erneut senden",

    MAGIC_LINK: "Magic Link",
    MAGIC_LINK_ACTION: "Magic Link senden",
    MAGIC_LINK_DESCRIPTION: "Lassen Sie sich einen Anmeldelink per E-Mail zusenden.",
    MAGIC_LINK_EMAIL: "Prüfen Sie Ihre E-Mails auf den Magic Link.",

    EMAIL_OTP: "E-Mail-Code",
    EMAIL_OTP_SEND_ACTION: "Code senden",
    EMAIL_OTP_VERIFY_ACTION: "Code bestätigen",
    EMAIL_OTP_DESCRIPTION: "Fordern Sie einen Bestätigungscode per E-Mail an.",
    EMAIL_OTP_VERIFICATION_SENT: "Der Bestätigungscode wurde per E-Mail gesendet.",
    SEND_VERIFICATION_CODE: "Bestätigungscode senden",
    RESEND_CODE: "Code erneut senden",

    PROVIDERS: "Anbieter",
    PROVIDERS_DESCRIPTION: "Melden Sie sich mit einem verbundenen Anbieter an.",
    DISABLED_CREDENTIALS_DESCRIPTION: "Wählen Sie einen Anbieter zur Anmeldung.",
    OR_CONTINUE_WITH: "Oder fortfahren mit",
    LINK: "Verknüpfen",
    UNLINK: "Verknüpfung aufheben",

    AVATAR: "Avatar",
    AVATAR_DESCRIPTION: "Verwalten Sie Ihr Profilbild.",
    AVATAR_INSTRUCTIONS: "Laden Sie ein neues Profilbild hoch.",
    UPLOAD_AVATAR: "Avatar hochladen",
    DELETE_AVATAR: "Avatar löschen",

    SETTINGS: "Einstellungen",
    SECURITY: "Sicherheit",

    SESSIONS: "Sitzungen",
    SESSIONS_DESCRIPTION: "Verwalten Sie Ihre aktiven Sitzungen.",
    CURRENT_SESSION: "Aktuelle Sitzung",
    SIGN_OUT: "Abmelden",

    SET_PASSWORD: "Passwort festlegen",
    SET_PASSWORD_DESCRIPTION: "Senden Sie sich eine E-Mail, um ein Passwort festzulegen.",

    CHANGE_PASSWORD: "Passwort ändern",
    CHANGE_PASSWORD_DESCRIPTION: "Ändern Sie Ihr aktuelles Passwort.",
    CHANGE_PASSWORD_INSTRUCTIONS: "Verwenden Sie ein sicheres Passwort.",
    CHANGE_PASSWORD_SUCCESS: "Das Passwort wurde erfolgreich geändert.",

    TWO_FACTOR: "Zwei-Faktor-Authentifizierung",
    TWO_FACTOR_ACTION: "Bestätigen",
    TWO_FACTOR_DESCRIPTION: "Geben Sie den Bestätigungscode ein.",
    TWO_FACTOR_CARD_DESCRIPTION: "Schützen Sie Ihr Konto mit einer zusätzlichen Sicherheitsebene.",
    TWO_FACTOR_DISABLE_INSTRUCTIONS: "Bestätigen Sie mit Ihrem Passwort, um 2FA zu deaktivieren.",
    TWO_FACTOR_ENABLE_INSTRUCTIONS: "Bestätigen Sie mit Ihrem Passwort, um 2FA zu aktivieren.",
    TWO_FACTOR_ENABLED: "Die Zwei-Faktor-Authentifizierung wurde aktiviert.",
    TWO_FACTOR_DISABLED: "Die Zwei-Faktor-Authentifizierung wurde deaktiviert.",
    TWO_FACTOR_PROMPT: "Bestätigungscode eingeben",
    TWO_FACTOR_TOTP_LABEL: "Code aus der Authenticator-App",
    ENABLE_TWO_FACTOR: "Zwei-Faktor aktivieren",
    DISABLE_TWO_FACTOR: "Zwei-Faktor deaktivieren",
    FORGOT_AUTHENTICATOR: "Authenticator verloren?",
    RECOVER_ACCOUNT: "Konto wiederherstellen",
    RECOVER_ACCOUNT_ACTION: "Wiederherstellen",
    RECOVER_ACCOUNT_DESCRIPTION: "Verwenden Sie einen Backup-Code, um den Zugriff wiederherzustellen.",
    BACKUP_CODES: "Backup-Codes",
    BACKUP_CODES_DESCRIPTION: "Bewahren Sie diese Codes sicher auf.",
    BACKUP_CODE: "Backup-Code",
    BACKUP_CODE_PLACEHOLDER: "Backup-Code",
    BACKUP_CODE_REQUIRED: "Backup-Code ist erforderlich",
    ONE_TIME_PASSWORD: "Einmalpasswort",
    CONTINUE_WITH_AUTHENTICATOR: "Mit Authenticator fortfahren",
    TRUST_DEVICE: "Diesem Gerät vertrauen",

    PASSKEY: "Passkey",
    PASSKEYS: "Passkeys",
    PASSKEYS_DESCRIPTION: "Verwalten Sie Ihre Passkeys.",
    PASSKEYS_INSTRUCTIONS: "Nutzen Sie Passkeys für eine sichere Anmeldung ohne Passwort.",
    ADD_PASSKEY: "Passkey hinzufügen",

    API_KEY: "API-Schlüssel",
    API_KEYS: "API-Schlüssel",
    API_KEYS_DESCRIPTION: "Verwalten Sie Ihre API-Schlüssel.",
    API_KEYS_INSTRUCTIONS: "Erstellen und verwalten Sie API-Schlüssel für den Zugriff.",
    CREATE_API_KEY: "API-Schlüssel erstellen",
    CREATE_API_KEY_DESCRIPTION: "Erstellen Sie einen neuen API-Schlüssel.",
    API_KEY_NAME_PLACEHOLDER: "Name des API-Schlüssels",
    API_KEY_CREATED: "API-Schlüssel erstellt",
    CREATE_API_KEY_SUCCESS: "Der API-Schlüssel wurde erfolgreich erstellt.",
    DELETE_API_KEY: "API-Schlüssel löschen",
    DELETE_API_KEY_CONFIRM: "Möchten Sie diesen API-Schlüssel wirklich löschen?",
    REVOKE: "Widerrufen",
    EXPIRES: "Läuft ab",
    NEVER_EXPIRES: "Läuft nie ab",
    NO_EXPIRATION: "Kein Ablaufdatum",

    ORGANIZATION: "Organisation",
    ORGANIZATIONS: "Organisationen",
    ORGANIZATIONS_DESCRIPTION: "Verwalten Sie Ihre Organisationen.",
    ORGANIZATIONS_INSTRUCTIONS: "Erstellen oder verwalten Sie Organisationen.",
    CREATE_ORGANIZATION: "Organisation erstellen",
    CREATE_ORGANIZATION_SUCCESS: "Die Organisation wurde erfolgreich erstellt.",
    ORGANIZATION_NAME: "Organisationsname",
    ORGANIZATION_NAME_PLACEHOLDER: "Organisationsname",
    ORGANIZATION_NAME_DESCRIPTION: "Geben Sie den Namen der Organisation ein.",
    ORGANIZATION_NAME_INSTRUCTIONS: "Wählen Sie einen eindeutigen Namen.",
    ORGANIZATION_SLUG: "Organisations-Slug",
    ORGANIZATION_SLUG_PLACEHOLDER: "organisations-slug",
    ORGANIZATION_SLUG_DESCRIPTION: "Geben Sie den Slug der Organisation ein.",
    ORGANIZATION_SLUG_INSTRUCTIONS: "Nur Kleinbuchstaben, Zahlen und Bindestriche verwenden.",
    MANAGE_ORGANIZATION: "Organisation verwalten",
    DELETE_ORGANIZATION: "Organisation löschen",
    DELETE_ORGANIZATION_DESCRIPTION: "Diese Aktion kann nicht rückgängig gemacht werden.",
    DELETE_ORGANIZATION_INSTRUCTIONS: "Bestätigen Sie zur Löschung den Organisationsnamen.",
    DELETE_ORGANIZATION_SUCCESS: "Die Organisation wurde gelöscht.",
    LEAVE_ORGANIZATION: "Organisation verlassen",
    LEAVE_ORGANIZATION_CONFIRM: "Möchten Sie diese Organisation wirklich verlassen?",
    LEAVE_ORGANIZATION_SUCCESS: "Die Organisation wurde verlassen.",
    SLUG_REQUIRED: "Slug ist erforderlich",
    SLUG_DOES_NOT_MATCH: "Der Slug stimmt nicht überein",

    MEMBERS: "Mitglieder",
    MEMBERS_DESCRIPTION: "Verwalten Sie die Mitglieder der Organisation.",
    MEMBERS_INSTRUCTIONS: "Laden Sie Mitglieder ein oder entfernen Sie sie.",
    INVITE_MEMBER: "Mitglied einladen",
    INVITE_MEMBER_DESCRIPTION: "Laden Sie ein neues Mitglied zur Organisation ein.",
    SEND_INVITATION: "Einladung senden",
    SEND_INVITATION_SUCCESS: "Die Einladung wurde gesendet.",
    PENDING_INVITATIONS: "Ausstehende Einladungen",
    PENDING_INVITATIONS_DESCRIPTION: "Diese Einladungen wurden noch nicht angenommen.",
    PENDING_USER_INVITATIONS_DESCRIPTION: "Ihre ausstehenden Einladungen.",
    CANCEL_INVITATION: "Einladung abbrechen",
    INVITATION_CANCELLED: "Die Einladung wurde abgebrochen.",
    ACCEPT_INVITATION: "Einladung annehmen",
    ACCEPT_INVITATION_DESCRIPTION: "Nehmen Sie die Einladung an, um beizutreten.",
    INVITATION_ACCEPTED: "Die Einladung wurde angenommen.",
    INVITATION_REJECTED: "Die Einladung wurde abgelehnt.",
    INVITATION_EXPIRED: "Die Einladung ist abgelaufen.",
    REMOVE_MEMBER: "Mitglied entfernen",
    REMOVE_MEMBER_CONFIRM: "Möchten Sie dieses Mitglied wirklich entfernen?",
    REMOVE_MEMBER_SUCCESS: "Das Mitglied wurde entfernt.",
    ROLE: "Rolle",
    SELECT_ROLE: "Rolle auswählen",
    UPDATE_ROLE: "Rolle aktualisieren",
    UPDATE_ROLE_DESCRIPTION: "Ändern Sie die Rolle dieses Mitglieds.",
    MEMBER_ROLE_UPDATED: "Die Rolle wurde aktualisiert.",
    ADMIN: "Administrator",
    MEMBER: "Mitglied",
    GUEST: "Gast",
    OWNER: "Inhaber",
    ACCEPT: "Annehmen",
    REJECT: "Ablehnen",

    TEAM: "Team",
    TEAMS: "Teams",
    TEAMS_DESCRIPTION: "Verwalten Sie Ihre Teams.",
    TEAM_ACTIVE: "Aktives Team",
    TEAM_SET_ACTIVE: "Als aktives Team festlegen",
    CREATE_TEAM: "Team erstellen",
    CREATE_TEAM_INSTRUCTIONS: "Geben Sie die Details für das neue Team ein.",
    CREATE_TEAM_SUCCESS: "Das Team wurde erstellt.",
    UPDATE_TEAM: "Team aktualisieren",
    UPDATE_TEAM_DESCRIPTION: "Ändern Sie die Teamdetails.",
    UPDATE_TEAM_SUCCESS: "Das Team wurde aktualisiert.",
    UPDATE_TEAMS: "Teams aktualisieren",
    UPDATE_TEAMS_DESCRIPTION: "Aktualisieren Sie die Teamzuordnung.",
    SELECT_TEAMS: "Teams auswählen",
    TEAM_NAME: "Teamname",
    TEAM_NAME_PLACEHOLDER: "Teamname",
    TEAM_NAME_DESCRIPTION: "Geben Sie den Namen des Teams ein.",
    TEAM_NAME_INSTRUCTIONS: "Wählen Sie einen eindeutigen Teamnamen.",
    TEAM_NAME_REQUIRED: "Teamname ist erforderlich",
    TEAM_NAME_DOES_NOT_MATCH: "Der Teamname stimmt nicht überein",
    DELETE_TEAM: "Team löschen",
    DELETE_TEAM_DESCRIPTION: "Diese Aktion kann nicht rückgängig gemacht werden.",
    DELETE_TEAM_INSTRUCTIONS: "Bestätigen Sie zur Löschung den Teamnamen.",
    DELETE_TEAM_SUCCESS: "Das Team wurde gelöscht.",
    REMOVE_TEAM_CONFIRM: "Möchten Sie dieses Team wirklich entfernen?",
    TEAM_MEMBERS: "Teammitglieder",
    TEAM_MEMBERS_DESCRIPTION: "Verwalten Sie die Mitglieder dieses Teams.",
    ADD_TEAM_MEMBER: "Teammitglied hinzufügen",
    ADD_TEAM_MEMBER_SUCCESS: "Das Teammitglied wurde hinzugefügt.",
    REMOVE_TEAM_MEMBER: "Teammitglied entfernen",
    REMOVE_TEAM_MEMBER_CONFIRM: "Möchten Sie dieses Teammitglied wirklich entfernen?",
    REMOVE_TEAM_MEMBER_SUCCESS: "Das Teammitglied wurde entfernt.",
    MANAGE_TEAM_MEMBERS: "Teammitglieder verwalten",
    MANAGE_TEAM_MEMBERS_DESCRIPTION: "Rollen und Mitgliedschaften verwalten.",
    USER_TEAMS_DESCRIPTION: "Teams, denen dieser Benutzer angehört.",
    NO_TEAMS_FOUND: "Keine Teams gefunden",
    MEMBER_SINGULAR: "Mitglied",
    MEMBER_PLURAL: "Mitglieder",

    ADD: "Hinzufügen",
    REMOVE: "Entfernen",
    CANCEL: "Abbrechen",
    CONTINUE: "Weiter",
    COPY_TO_CLIPBOARD: "In Zwischenablage kopieren",
    COPY_ALL_CODES: "Alle Codes kopieren",
    COPIED_TO_CLIPBOARD: "In Zwischenablage kopiert",
    DELETE: "Löschen",
    DONE: "Fertig",
    GO_BACK: "Zurück",
    LOGO: "Logo",
    LOGO_DESCRIPTION: "Verwalten Sie das Logo.",
    LOGO_INSTRUCTIONS: "Laden Sie ein neues Logo hoch.",
    OPTIONAL_BRACKETS: "(optional)",
    PRIVACY_POLICY: "Datenschutzerklärung",
    PROTECTED_BY_RECAPTCHA: "Diese Website ist durch reCAPTCHA geschützt.",
    BY_CONTINUING_YOU_AGREE: "Mit dem Fortfahren stimmen Sie den",
    REQUEST_FAILED: "Anfrage fehlgeschlagen",
    SAVE: "Speichern",
    UPDATE: "Aktualisieren",
    UPDATED_SUCCESSFULLY: "Erfolgreich aktualisiert",
    UPLOAD: "Hochladen",
    UPLOAD_LOGO: "Logo hochladen",
    DELETE_LOGO: "Logo löschen",
    UNKNOWN: "Unbekannt",
    TERMS_OF_SERVICE: "Nutzungsbedingungen",
    REMEMBER_ME: "Angemeldet bleiben",
    SESSION_NOT_FRESH: "Die Sitzung ist nicht mehr aktuell. Bitte erneut anmelden.",
    IS_INVALID: "ist ungültig",
    IS_REQUIRED: "ist erforderlich",
    IS_THE_SAME: "ist unverändert",

    DELETE_ACCOUNT: "Konto löschen",
    DELETE_ACCOUNT_DESCRIPTION: "Diese Aktion kann nicht rückgängig gemacht werden.",
    DELETE_ACCOUNT_INSTRUCTIONS: "Bestätigen Sie zur Löschung Ihr Konto.",
    DELETE_ACCOUNT_VERIFY: "Bitte bestätigen Sie die Kontolöschung.",
    DELETE_ACCOUNT_SUCCESS: "Das Konto wurde gelöscht."
} as const;
